# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_vehiculo.ui'
#
# Created: Fri Jul  5 12:58:04 2013
#      by: pyside-uic 0.2.13 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(517, 397)
        self.btn_ok = QtGui.QPushButton(Dialog)
        self.btn_ok.setGeometry(QtCore.QRect(350, 350, 98, 27))
        self.btn_ok.setObjectName("btn_ok")
        self.btn_cancel = QtGui.QPushButton(Dialog)
        self.btn_cancel.setGeometry(QtCore.QRect(240, 350, 98, 27))
        self.btn_cancel.setObjectName("btn_cancel")
        self.layoutWidget = QtGui.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(120, 10, 131, 331))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.le_modelo = QtGui.QLineEdit(self.layoutWidget)
        self.le_modelo.setText("")
        self.le_modelo.setObjectName("le_modelo")
        self.verticalLayout_2.addWidget(self.le_modelo)
        self.le_color = QtGui.QLineEdit(self.layoutWidget)
        self.le_color.setObjectName("le_color")
        self.verticalLayout_2.addWidget(self.le_color)
        self.le_motor = QtGui.QLineEdit(self.layoutWidget)
        self.le_motor.setObjectName("le_motor")
        self.verticalLayout_2.addWidget(self.le_motor)
        self.le_peso = QtGui.QLineEdit(self.layoutWidget)
        self.le_peso.setObjectName("le_peso")
        self.verticalLayout_2.addWidget(self.le_peso)
        self.le_descripcion = QtGui.QLineEdit(self.layoutWidget)
        self.le_descripcion.setObjectName("le_descripcion")
        self.verticalLayout_2.addWidget(self.le_descripcion)
        self.le_rendimiento = QtGui.QLineEdit(self.layoutWidget)
        self.le_rendimiento.setObjectName("le_rendimiento")
        self.verticalLayout_2.addWidget(self.le_rendimiento)
        self.sb_fecha = QtGui.QSpinBox(self.layoutWidget)
        self.sb_fecha.setMinimum(1900)
        self.sb_fecha.setMaximum(2013)
        self.sb_fecha.setProperty("value", 2013)
        self.sb_fecha.setObjectName("sb_fecha")
        self.verticalLayout_2.addWidget(self.sb_fecha)
        self.cb_marca = QtGui.QComboBox(self.layoutWidget)
        self.cb_marca.setObjectName("cb_marca")
        self.verticalLayout_2.addWidget(self.cb_marca)
        self.cb_tipo = QtGui.QComboBox(self.layoutWidget)
        self.cb_tipo.setObjectName("cb_tipo")
        self.verticalLayout_2.addWidget(self.cb_tipo)
        self.layoutWidget_3 = QtGui.QWidget(Dialog)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 10, 111, 328))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtGui.QLabel(self.layoutWidget_3)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtGui.QLabel(self.layoutWidget_3)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtGui.QLabel(self.layoutWidget_3)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtGui.QLabel(self.layoutWidget_3)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = QtGui.QLabel(self.layoutWidget_3)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_6 = QtGui.QLabel(self.layoutWidget_3)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.label_8 = QtGui.QLabel(self.layoutWidget_3)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.label_9 = QtGui.QLabel(self.layoutWidget_3)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.label_10 = QtGui.QLabel(self.layoutWidget_3)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.layoutWidget_2 = QtGui.QWidget(Dialog)
        self.layoutWidget_2.setGeometry(QtCore.QRect(250, 10, 258, 328))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_7 = QtGui.QLabel(self.layoutWidget_2)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.le_imagen = QtGui.QLineEdit(self.layoutWidget_2)
        self.le_imagen.setReadOnly(True)
        self.le_imagen.setObjectName("le_imagen")
        self.horizontalLayout_5.addWidget(self.le_imagen)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.graphicsView = QtGui.QGraphicsView(self.layoutWidget_2)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout_3.addWidget(self.graphicsView)
        self.btn_agregar = QtGui.QPushButton(self.layoutWidget_2)
        self.btn_agregar.setObjectName("btn_agregar")
        self.verticalLayout_3.addWidget(self.btn_agregar)
        self.btn_marca = QtGui.QPushButton(self.layoutWidget_2)
        self.btn_marca.setObjectName("btn_marca")
        self.verticalLayout_3.addWidget(self.btn_marca)
        self.btn_tipo = QtGui.QPushButton(self.layoutWidget_2)
        self.btn_tipo.setObjectName("btn_tipo")
        self.verticalLayout_3.addWidget(self.btn_tipo)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Formulario Vehiculo", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_ok.setText(QtGui.QApplication.translate("Dialog", "Aceptar", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_cancel.setText(QtGui.QApplication.translate("Dialog", "Cancelar", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Modelo:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Color:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Motor:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Peso:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Descripción:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "Rendimiento:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog", "Fecha Creación:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog", "Marca:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Dialog", "Tipo:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "Imagen:", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_agregar.setText(QtGui.QApplication.translate("Dialog", "Agregar Imagen", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_marca.setText(QtGui.QApplication.translate("Dialog", "Nueva Marca", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_tipo.setText(QtGui.QApplication.translate("Dialog", "Nuevo Tipo", None, QtGui.QApplication.UnicodeUTF8))

